### ISSUE TITLE
Perfrormance Query

### ISSUE THREAD

**Issue by JamesOwen7** [ddtch/react-native-libre-manager#2]
This isn't an issue but I couldn't find another way to contact either of the contributors.

I'm new to RN and to no surprise am developing an app which reads data from a glucose sensor and then displays this in a graph. I wanted to know whether this package has these capabilties with the libre 2?

Do you have an example script of it being used?

**Comment by JamesOwen7** [comment]
Oh and does it run on android or only iOS?

**Comment by ddtch** [comment]
@JamesOwen7  support libre devices you can see in the readme file. Building charts is up to you. We provide only API to read data from sensors. You can use the method `getGlucoseHistory` to retire data. Responses are [described here](https://github.com/ddtch/react-native-libre-manager/blob/master/src/index.ts)
